// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQHIrTCNWwB02APIY6Q9VMJT2jzkqwYE',
    appId: '1:212110431805:web:f9e7f7fdcb9bb916063c54',
    messagingSenderId: '212110431805',
    projectId: 'what-s-app-clone-6ef58',
    authDomain: 'what-s-app-clone-6ef58.firebaseapp.com',
    storageBucket: 'what-s-app-clone-6ef58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2laorGOvdg5eP9LvWiaOPmiO0Z3g3MuQ',
    appId: '1:212110431805:android:d065f2f58c2375b5063c54',
    messagingSenderId: '212110431805',
    projectId: 'what-s-app-clone-6ef58',
    storageBucket: 'what-s-app-clone-6ef58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFhIUXLFdjyiiSwqUtYAsfvH0EmED2PuY',
    appId: '1:212110431805:ios:c978567a980db054063c54',
    messagingSenderId: '212110431805',
    projectId: 'what-s-app-clone-6ef58',
    storageBucket: 'what-s-app-clone-6ef58.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFhIUXLFdjyiiSwqUtYAsfvH0EmED2PuY',
    appId: '1:212110431805:ios:c978567a980db054063c54',
    messagingSenderId: '212110431805',
    projectId: 'what-s-app-clone-6ef58',
    storageBucket: 'what-s-app-clone-6ef58.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJQHIrTCNWwB02APIY6Q9VMJT2jzkqwYE',
    appId: '1:212110431805:web:416db4caf30be7b4063c54',
    messagingSenderId: '212110431805',
    projectId: 'what-s-app-clone-6ef58',
    authDomain: 'what-s-app-clone-6ef58.firebaseapp.com',
    storageBucket: 'what-s-app-clone-6ef58.firebasestorage.app',
  );

}